name: Check

on:
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch: # manual button click

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Flox environment
        uses: ./.github/actions/setup-flox

      - name: Install Python dependencies
        run: flox activate -c "uv sync --frozen"
        shell: bash

      - name: Check (lint)
        run: flox activate -c "make check"
        shell: bash
