name: Test-CPU

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "**"
      - "!**.md"
      - "!**.rst"
      - "!docs/**"
      - "!.bumpversion.toml"
      - "!.gitignore"
      - "!**.cu"
      - "!**.h"
      - "!CMakeLists.txt"
      - "!.github/workflows/*.yml"
      - ".github/workflows/test_cpu.yml"
  workflow_dispatch: # manual button click

defaults:
  run:
    shell: bash

jobs:
  test-cpu:
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache downloaded data
        uses: actions/cache@v4
        with:
          path: ~/.cache/mach
          # Key based on known file hashes from cached_download() calls
          key: mach-data-cache-v1-${{ runner.os }}-c93af0781daeebf771e53a42a629d4f311407410166ef2f1d227e9d2a1b8c641-c349dc1d677c561434fd0e4a74142c4a0a44b7e6ae0a42d446c078a528ef58c1

      - name: Install nvcc (CUDA compiler)
        uses: Jimver/cuda-toolkit@v0.2.25
        id: cuda-toolkit
        with:
          method: "network"
          sub-packages: '["nvcc"]'

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run CPU-only unit tests
        run: uv run --group test --group array pytest tests -v -s -m "no_cuda"
